name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: uvx ruff check .
      - run: uvx ruff format --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: uv sync
      - run: uv pip check
      # Waiting for fixes for vulnerabilities in ollama v0.6.1 and PyJWT v2.12.1
      - run: |
          uv run pip-audit \
            --ignore-vuln PYSEC-2025-146 \
            --ignore-vuln PYSEC-2025-144 \
            --ignore-vuln PYSEC-2025-147 \
            --ignore-vuln PYSEC-2025-145 \
            --ignore-vuln PYSEC-2026-102 \
            --ignore-vuln PYSEC-2026-101 \
            --ignore-vuln PYSEC-2025-183
      - run: uv run pytest
